# Basis-Image für Node.js (Angular wird darüber installiert)
FROM node:18

# Arbeitsverzeichnis setzen
WORKDIR /app

# Kopiere package.json und package-lock.json (falls vorhanden)
COPY ./app/GAEP/package*.json ./

# Installiere Angular und andere Abhängigkeiten
RUN npm install -g @angular/cli@18 && npm install

# Exponiere den Entwicklungsport 4200 und den API-Port (falls nötig)
EXPOSE 4200

WORKDIR /app/GAEP

# Befehl für den Entwicklungsmodus (Angular Live Server)
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "1000"]
