version: '3.8'

services:
  gaep-frontend:
    build: .
    container_name: gaep-frontend
    image: gaep-angular-frontend
    ports:
      - "80:80"  # Port-Freigabe für das Webhosting
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production  # Optional, falls du Umgebungsvariablen brauchst
