# Basis-Image mit Python 3.9.2
FROM python:3.9.2-slim

# install sqlite3 Version 3.46.1
ARG SQLITE_VERSION=3460100
RUN apt-get update && \
    apt-get install -y wget gcc make build-essential && \
    wget https://www.sqlite.org/2024/sqlite-autoconf-$SQLITE_VERSION.tar.gz && \
    tar xzf sqlite-autoconf-$SQLITE_VERSION.tar.gz && \
    cd sqlite-autoconf-$SQLITE_VERSION && \
    ./configure && \
    make && \
    make install && \
	echo 'export PATH=$HOME/opt/sqlite/bin:$PATH' >> ~/.bash_profile && \
    echo 'export LD_LIBRARY_PATH=$HOME/opt/sqlite/lib' >> ~/.bash_profile && \
    echo 'export LD_RUN_PATH=$HOME/opt/sqlite/lib' >> ~/.bash_profile && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /sqlite-autoconf-$SQLITE_VERSION*
	
	
WORKDIR /

# Kopieren der requirements.txt in das Arbeitsverzeichnis
COPY requirements.txt .

# Installation der Python-Pakete
RUN pip install --no-cache-dir -r requirements.txt

# Arbeitsverzeichnis setzen
WORKDIR /app

# Kopieren des restlichen Codes ins Arbeitsverzeichnis (optional)
#COPY . .

# Default-Befehl zum Starten des Containers (optional, falls ein Startbefehl nötig ist)
#CMD ["python", "app.py"]